# Application properties
spring.application.name=account
SERVER.PORT = 8011

# Database connection details
spring.datasource.url=jdbc:mysql://localhost:3306/account
spring.datasource.username=yusufcandmrz
spring.datasource.password=yusufcandmrz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true