# Application properties
spring.application.name=auth
SERVER.PORT=8010

# Database connection details
spring.datasource.url=jdbc:mysql://localhost:3306/auth
spring.datasource.username=yusufcandmrz
spring.datasource.password=yusufcandmrz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Cloud configuration
spring.cloud.config.enabled=false

# Apache Kafka configuration
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
